workflows:
  ionic-capacitor-android-workflow:
    name: Ionic Capacitor Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - davidKeystore
      groups:
        - google_play_credentials
        - githubPassword
        - githubToken
      vars:
        PACKAGE_NAME: "io.codemagic.dtrdic8"
    triggering:
          events:
              - pull_request
              - push
              - tag
          branch_patterns:
          - pattern: "main" 
            include: true
            source: false
    scripts:
      - name: Install npm dependencies for Ionic project
        script: |
          npm install
      - name: Set up local.properties
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Update dependencies and copy web assets to native project
        script: | 
          npx cap sync
      - name: Build Android release
        script: | 
          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
          if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
            # fallback in case no build number was found from Google Play.
            # Alternatively, you can `exit 1` to fail the build
            # BUILD_NUMBER is a Codemagic built-in variable tracking the number
            # of times this workflow has been built
            UPDATED_BUILD_NUMBER=$BUILD_NUMBER
          else
            UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
          fi
          cd android
          ./gradlew bundleRelease \
            -PversionCode=$UPDATED_BUILD_NUMBER \
            -PversionName=1.0.$UPDATED_BUILD_NUMBER
    artifacts:
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - david@nevercode.io
        notify:
          success: true
          failure: false
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
      scripts:
        - name: Push git tags
          script: | 
            # set -e # exit on first failed command
            # set -x # print all executed commands to the log

            # new_version=v1.0.$BUILD_NUMBER
            # git tag $new_version
            # git push "https://dtrdic:$GITHUB_TOKEN@github.com/ionicTestApp4.git" --tags

            # if [ "$CM_BUILD_STEP_STATUS" = "success" ]
            # then
            #   new_version=v1.0.$BUILD_NUMBER
            #   git tag $new_version
            # git push "https://dtrdic:$GITHUB_TOKEN@github.com/ionicTestApp4.git" --tags
            # fi

       
            if [ -f ~/SUCCESS ]; then
              echo "GOOGLE_PLAY_PUBLISHING=true" > $CM_ENV
              echo "the value of cm_env now is:" $CM_ENV
              fi
